// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWct-0pAnASuqedNAmjAjH2xbxlAHbbas',
    appId: '1:387706165372:web:2b1ff6e3677d68bd0e51f9',
    messagingSenderId: '387706165372',
    projectId: 'crudfirestore-f14dc',
    authDomain: 'crudfirestore-f14dc.firebaseapp.com',
    storageBucket: 'crudfirestore-f14dc.appspot.com',
    measurementId: 'G-DCL8NS78TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClbSr6gn8UFAHdRaz_t7U_aNUuKw-csQg',
    appId: '1:387706165372:android:8fb60c9154630e900e51f9',
    messagingSenderId: '387706165372',
    projectId: 'crudfirestore-f14dc',
    storageBucket: 'crudfirestore-f14dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjmpZs82vA4duIdrcZ5R44_83tsmGWw8',
    appId: '1:387706165372:ios:17b66177817221a70e51f9',
    messagingSenderId: '387706165372',
    projectId: 'crudfirestore-f14dc',
    storageBucket: 'crudfirestore-f14dc.appspot.com',
    iosBundleId: 'com.example.firebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgjmpZs82vA4duIdrcZ5R44_83tsmGWw8',
    appId: '1:387706165372:ios:dcdcf034ac3d2de00e51f9',
    messagingSenderId: '387706165372',
    projectId: 'crudfirestore-f14dc',
    storageBucket: 'crudfirestore-f14dc.appspot.com',
    iosBundleId: 'com.example.firebaseFirestore.RunnerTests',
  );
}
